name: Generate sphinx venv

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform all steps to create the venv
        run: |
          export PYVER="$(cat PYVER)"
          export RLTAG="py$PYVER-$(date +%Y%m%d)"
          export FNAME="sphinx-$RLTAG-$(uname -m)-venv-mbs"
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get -y install software-properties-common xz-utils
          sudo add-apt-repository -y ppa:deadsnakes/nightly
          sudo apt-get -y install python"$PYVER"-dev python"$PYVER"-venv
          sudo mkdir -p /root/mbs/extras
          sudo python"$PYVER" -m venv /root/mbs/extras/sphinx
          sudo /root/mbs/extras/sphinx/bin/pip install sphinx recommonmark myst-parser
          sudo mv /root/mbs/extras/sphinx ./"$FNAME"
          sudo tar -cf "$FNAME".tar "$FNAME"
          sudo chown "$(whoami):$(whoami)" "$FNAME".tar
          xz -v9e "$FNAME".tar
          echo "$FNAME".tar.xz > .ASSET_NAME
          echo "$RLTAG" > .TAG_NAME

      - name: Create nightly release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="$(cat .TAG_NAME)"
          asset="$(cat .ASSET_NAME)"
          if gh release view "$tag" &>/dev/null; then
            echo "Release $tag already exists. Not creating a new release." >&2
            exit 0
          fi
          gh release create "$tag" --title "$tag" "$asset"
